# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "riscvm"

[options]
RISCVM_DIRECT_DISPATCH = false
RISCVM_CODE_ENCRYPTION = false
RISCVM_OPCODE_SHUFFLING = false
RISCVM_DEBUG_SYSCALLS = true
RISCVM_SILENT_PANIC = false
RISCVM_TRACING = false
RISCVM_CUSTOM_SYSCALLS = false

[target.riscvm-options]
type = "interface"
compile-features = ["cxx_std_17"]
RISCVM_DIRECT_DISPATCH.compile-definitions = ["DIRECT_DISPATCH"]
RISCVM_SILENT_PANIC.compile-definitions = ["SILENT_PANIC"]
RISCVM_TRACING.compile-definitions = ["TRACING"]
clang-cl.compile-options = ["/clang:-fno-jump-tables", "/clang:-fno-slp-vectorize", "/clang:-fno-vectorize", "/clang:-mno-sse"]
clang.compile-options = ["-fno-jump-tables", "-fno-slp-vectorize", "-fno-vectorize"]
apple.compile-options = ["-Wno-deprecated-declarations"]
msvc.link-options = ["/DYNAMICBASE:NO", "/INCREMENTAL:NO"]
msvc.compile-definitions = ["_CRT_SECURE_NO_WARNINGS"]

[target.riscvm]
type = "executable"
sources = ["main.cpp", "riscvm.cpp"]
headers = ["riscvm.h", "opcodes.h", "shuffled_opcodes.h", "trace.h", "riscvm-code.h"]
RISCVM_DEBUG_SYSCALLS.compile-definitions = ["DEBUG_SYSCALLS"]
RISCVM_CODE_ENCRYPTION.compile-definitions = ["CODE_ENCRYPTION"]
RISCVM_OPCODE_SHUFFLING.compile-definitions = ["OPCODE_SHUFFLING"]
RISCVM_CUSTOM_SYSCALLS.compile-definitions = ["CUSTOM_SYSCALLS"]
link-libraries = ["riscvm-options"]

[target.tests]
type = "executable"
sources = ["tests.cpp", "riscvm.cpp"]
compile-definitions = ["CUSTOM_SYSCALLS"]
link-libraries = ["riscvm-options"]

[target.c2]
type = "executable"
sources = ["c2/c2.cpp", "riscvm.cpp"]
RISCVM_DEBUG_SYSCALLS.compile-definitions = ["DEBUG_SYSCALLS"]
RISCVM_CODE_ENCRYPTION.compile-definitions = ["CODE_ENCRYPTION"]
RISCVM_OPCODE_SHUFFLING.compile-definitions = ["OPCODE_SHUFFLING"]
RISCVM_CUSTOM_SYSCALLS.compile-definitions = ["CUSTOM_SYSCALLS"]
link-libraries = ["riscvm-options"]
windows.link-libraries = ["ws2_32.lib"]

# Only for IDE purposes, not actually built here
[target.riscvm-crt0]
type = "custom"
sources = ["lib/crt0.c"]
