[project]
name = "obfuscator"
msvc-runtime = "static"

[options]
BUILD_TESTS = "root"

[variables]
INSTALL_GTEST = false

[fetch-content.zasm]
git = "https://github.com/zyantific/zasm"
tag = "a18fa34251b161cc18e4c0fc385dee7cea104cfd"

[fetch-content.googletest]
git = "https://github.com/google/googletest"
tag = "v1.15.2"
condition = "build-tests"

[fetch-content.args]
git = "https://github.com/LLVMParty/args"
tag = "v1.0"

[fetch-content.fmt]
url = "https://github.com/fmtlib/fmt/releases/download/10.2.1/fmt-10.2.1.zip"
sha256 = "312151a2d13c8327f5c9c586ac6cf7cddc1658e8f53edae0ec56509c8fa516c9"

[fetch-content.linux-pe]
git = "https://github.com/can1357/linux-pe"
tag = "be6d1f6fc30fb8058b5220e0bb2652a6dc8ec0b0"

[fetch-content.json]
url = "https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz"
sha256 = "d6c65aca6b1ed68e7a182f4757257b107ae403032760ed6ef121c9d55e81757d"

[target.obfuscator]
type = "static"
alias = "riscvm::obfuscator"
sources = ["src/obfuscator/*.cpp"]
headers = ["include/obfuscator/*.hpp"]
include-directories = ["include"]
compile-features = ["cxx_std_20"]
link-libraries = ["zasm::zasm", "linux-pe", "fmt::fmt"]

[target.obfuscate]
condition = "root"
type = "executable"
sources = ["src/obfuscate.cpp"]
link-libraries = ["riscvm::obfuscator", "args::args", "nlohmann_json::nlohmann_json"]

[target.tests]
type = "executable"
condition = "build-tests"
sources = ["src/tests/*.cpp"]
link-libraries = ["riscvm::obfuscator", "gtest_main"]
