# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.19"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "payload"
cmake-before = "set(CMAKE_CONFIGURATION_TYPES Debug Release)"
include-after = ["cmake/riscvm.cmake"]
msvc-runtime = "static"

[template.riscvm]
type = "executable"
add-function = "add_riscvm_executable"
msvc.compile-options = ["/GR-", "/EHs-"]
clang.compile-options = ["-fno-exceptions", "-fno-rtti"]
compile-definitions = ["_HAS_EXCEPTIONS=0"] # TODO: MSVC only?

# Windows implementation of the riscvm syscalls (for debugging only)
[target.riscvm-crt0]
type = "shared"
sources = ["crt/riscvm-crt0.cpp"]

[target.payload]
type = "riscvm"
sources = [
    "src/main.c",
    "crt/minicrt.c",
    #"crt/minicrt.cpp",
]
headers = [
    "include/phnt.h",
]
include-directories = [
    "include",
]
link-libraries = [
    "riscvm-crt0",
    "ntdll.lib",
]
compile-features = ["cxx_std_17"]
msvc.link-options = [
    "/INCREMENTAL:NO",
    "/DEBUG",
]
